version: '3.2'
services:
    haproxy:
        container_name: haproxy
        image: polyverse/docker-haproxy-rsyslog
        ports:
            - "80:80"
            - "443:443"
        environment:
            - CERTS=play.polyverse.io
            - EMAIL=archis@polyverse.io
        volumes:
            - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
            - /etc/letsencrypt:/etc/letsencrypt
    pwd:
        # pwd daemon container always needs to be named this way
        container_name: pwd
        # use the latest golang image
        image: golang
        # go to the right place and starts the app
        command: /bin/sh -c 'ssh-keygen -N "" -t rsa -f /etc/ssh/ssh_host_rsa_key >/dev/null; cd /go/src/github.com/polyverse/play-with-polyverse; go run api.go -save /pwd/sessions -name l2 -default-session-duration 1h30m -playground-domain play.polyverse.io -default-dind-image polyverse/dind-alpine -cookie-hash-key '"'"'$CookieHashKey'"'"' -cookie-block-key '"'"'$CookieBlockKey'"'"''
        environment:
            - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
            - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
            - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
            - FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
            - CookieHashKey=${CookieHashKey}
            - CookieBlockKey=${CookieBlockKey}
        volumes:
            # since this app creates networks and launches containers, we need to talk to docker daemon
            - /var/run/docker.sock:/var/run/docker.sock
            # mount the box mounted shared folder to the container
            - $GOPATH/src:/go/src
            - sessions:/pwd
    l2:
        container_name: l2
        # use the latest golang image
        image: golang
        # go to the right place and starts the app
        command: /bin/sh -c 'ssh-keygen -N "" -t rsa -f /etc/ssh/ssh_host_rsa_key >/dev/null; cd /go/src/github.com/polyverse/play-with-polyverse/router/l2; go run l2.go -ssh_key_path /etc/ssh/ssh_host_rsa_key -name l2 -save /pwd/networks'
        volumes:
            - $GOPATH/src:/go/src
            - /var/run/docker.sock:/var/run/docker.sock
            - networks:/pwd
        ports:
            - "8022:22"
            - "8053:53"
            - "8443:443"
volumes:
    sessions:
    networks:
